name: 'look for past due reminders and notify'

on:
  schedule:
    - cron: "0 9-17/2 * * 1-5"
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
    - name: check reminders and notify
      uses: agrc/reminder-action@v1.0.0
